using System.Text;
using System.Threading.Tasks;

namespace TownShip_Form.Kernal
{
    public enum PriorityTag
    {
        one = 1,
        two = 2,
        three = 3
    };
    public enum ProductTag
    {
        ptNotFound = 0,
        ptPhenica = 1,
        ptKukuruza = 2,
        ptMorkov = 3,
        ptSaharniTrosnik = 4,
        ptHlopok = 5,
        ptKlubnika = 6,
        ptTomat = 7,
        ptSosna = 8,
        ptKartofel = 9,
        ptKakao = 10,
        ptKauchuk = 11,
        ptShelk = 12,
        ptPerec = 13,
        ptMoloko = 14,
        ptYaco = 15,
        ptSherst = 16,
        ptHleb = 17,
        ptPechenie = 18,
        ptBublic = 19,
        ptPizza = 20,
        ptKartofelHleb = 21,
        ptBananaHleb = 22,
        ptClivki = 23,
        ptSyr = 24,
        ptMaslo = 25,
        ptIogury = 26,
        ptPersikIogurt = 27,
        ptHlopokTkan = 28,
        ptPryaja = 29,
        ptShelkNit = 30,
        ptRubashka = 31,
        ptSviter = 32,
        ptPalto = 33,
        ptShlapa = 34,
        ptPlatie = 35,
        ptKostum = 36,
        ptPopkorn = 37,
        ptKukuruzaChips = 38,
        ptGranola = 39,
        ptChips = 40,
        ptMilkSheik = 41,
        ptChisburger = 42,
        ptSendvich = 43,
        ptKartoshkaFree = 44,
        ptPecheneiKartofel = 45,
        ptRezina = 46,
        ptPlastik = 47,
        ptKley = 48,
        ptSahar = 49,
        ptSirop = 50,
        ptKaramel = 51,
        ptMedovayaKaramel = 52,
        ptBumaga = 53,
        ptBumagaPolotence = 54,
        ptOboi = 55,
        ptKniga = 56,
        ptMorogenoe = 57,
        ptFruktLed = 58,
        ptZamarojeniIogurt = 59,
        ptEscimo = 60,
        ptAnanasSorbet = 61,
        ptKeks = 62,
        ptShokoladPirog = 63,
        ptPirojenoe = 64,
        ptPoncik = 65,
        ptChizkeyk = 66,
        ptkanope = 67,
        //корм для животных
        ptKormKorova = 68,
        prKormKurica = 69,
        ptKormOvca = 70,
        prKormPchela = 71,
        //фабрика джема
        ptKlubnikaVarenie = 72,
        ptPersikVarenie = 73,
        ptArbuzVarenie = 74,
        ptSlivaVarenie = 75,
        //фрукт с острова
        ptPersik = 76,
        ptArbuz = 77,
        ptSliva = 78,

        //
        ptSotiMed = 79,
        ptPlasticButilka = 80,
        ptToy = 81,
        //
        ptMedPrynic = 82,
        ptMyach = 83,

        ptVinograd = 84,
        ptOlivki = 85,
        ptLaym = 86,
        ptVinogradJele = 87,
        ptNaduvnayaLodka = 88,

        ptDraje = 89,
        ptIriska = 90,
        ptBanan = 91,
        ptBecon = 92,
        ptKormPig = 93,
        ptGlazirBecon = 94,
        ptKaramelPalochka = 95,
        ptChocolade = 96,
        ptSousChili = 97,
        ptBurrito = 98,
        ptNachos = 99,
        ptLaymPirog = 100,
        ptKokosMakaruna = 101,
        ptKokos = 102,
        ptLedenec = 103
    };
}
